version: '3'
services:
  backend:
    build:
      context: ./backend/backend_deu_project
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend/backend_deu_project:/app/backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app/frontend
