version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/backend_deu_project/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/app/backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend
