const presetExercises = [
  {
    id: 1,
    exerciseType: 'Velocidad',
    name: 'Velocidad Ligero',
    description: 'Entrenamiento enfocado en velocidad para principiantes',
    duration: 60,
    segments: [
      { segmentDuration: 15, cadence: 80, beatsPerMinute: 130 },
      { segmentDuration: 15, cadence: 85, beatsPerMinute: 135 },
      { segmentDuration: 15, cadence: 90, beatsPerMinute: 140 },
      { segmentDuration: 15, cadence: 95, beatsPerMinute: 145 },
    ],
  },
  {
    id: 2,
    exerciseType: 'Resistencia',
    name: 'Resistencia Ligero',
    description: 'Entrenamiento enfocado en resistencia para principiantes',
    duration: 90,
    segments: [
      { segmentDuration: 30, cadence: 70, beatsPerMinute: 120 },
      { segmentDuration: 30, cadence: 75, beatsPerMinute: 125 },
      { segmentDuration: 30, cadence: 80, beatsPerMinute: 130 },
    ],
  },
  {
    id: 3,
    exerciseType: 'Cadencia',
    name: 'Cadencia Ligero',
    description: 'Entrenamiento enfocado en cadencia para principiantes',
    duration: 60,
    segments: [
      { segmentDuration: 20, cadence: 85, beatsPerMinute: 130 },
      { segmentDuration: 20, cadence: 90, beatsPerMinute: 135 },
      { segmentDuration: 20, cadence: 95, beatsPerMinute: 140 },
    ],
  },
  {
    id: 4,
    exerciseType: 'Fuerza',
    name: 'Fuerza Ligero',
    description: 'Entrenamiento enfocado en fuerza para principiantes',
    duration: 30,
    segments: [
      { segmentDuration: 10, cadence: 60, beatsPerMinute: 110 },
      { segmentDuration: 10, cadence: 65, beatsPerMinute: 115 },
      { segmentDuration: 10, cadence: 70, beatsPerMinute: 120 },
    ],
  },
  {
    id: 5,
    exerciseType: 'Fuerza',
    name: 'Fuerza Intenso',
    description: 'Entrenamiento colina arriba para practicar fuerza. No apto para principiantes',
    duration: 45,
    segments: [
      { segmentDuration: 15, cadence: 55, beatsPerMinute: 100 },
      { segmentDuration: 15, cadence: 60, beatsPerMinute: 105 },
      { segmentDuration: 15, cadence: 65, beatsPerMinute: 110 },
    ],
  },
  {
    id: 6,
    exerciseType: 'Fuerza',
    name: 'Fuerza Intenso con Pausa',
    description: 'Similar a Fuerza Intenso pero con pausas mas largas entre segmentos',
    duration: 65,
    segments: [
      { segmentDuration: 20, cadence: 50, beatsPerMinute: 95 },
      { segmentDuration: 15, cadence: 55, beatsPerMinute: 100 },
      { segmentDuration: 20, cadence: 60, beatsPerMinute: 105 },
    ],
  },
  {
    id: 7,
    exerciseType: 'Resistencia',
    name: 'Tour de france',
    description: 'Entrenamiento extremo de aguante',
    duration: 430,
    segments: [
      { segmentDuration: 120, cadence: 70, beatsPerMinute: 120 },
      { segmentDuration: 120, cadence: 75, beatsPerMinute: 125 },
      { segmentDuration: 120, cadence: 80, beatsPerMinute: 130 },
    ],
  },
  {
    id: 8,
    exerciseType: 'Resistencia',
    name: 'Vuelta al mundo',
    description: 'Recorrido por todo el cuadrado de la plata',
    duration: 300,
    segments: [
      { segmentDuration: 80, cadence: 65, beatsPerMinute: 110 },
      { segmentDuration: 80, cadence: 70, beatsPerMinute: 115 },
      { segmentDuration: 80, cadence: 75, beatsPerMinute: 120 },
    ],
  },
  {
    id: 9,
    exerciseType: 'Velocidad',
    name: 'Carrera alterna',
    description: 'Camino por el bosque a maxima velocidad',
    duration: 40,
    segments: [
      { segmentDuration: 10, cadence: 90, beatsPerMinute: 140 },
      { segmentDuration: 10, cadence: 95, beatsPerMinute: 145 },
      { segmentDuration: 10, cadence: 100, beatsPerMinute: 150 },
    ],
  },
  {
    id: 10,
    exerciseType: 'Cadencia',
    name: 'Bici fija rpm',
    description: '20 minutos de calentamiento, ejercicio, 20 mins para bajar.',
    duration: 180,
    segments: [
      { segmentDuration: 20, cadence: 60, beatsPerMinute: 100 },
      { segmentDuration: 60, cadence: 85, beatsPerMinute: 135 },
      { segmentDuration: 60, cadence: 90, beatsPerMinute: 140 },
      { segmentDuration: 20, cadence: 60, beatsPerMinute: 100 },
    ],
  },
  {
    id: 11,
    exerciseType: 'Fuerza',
    name: 'Bici en cambio duro',
    description: '10 minutos de calentamiento en configuracion tranqui, luego cambio a duro sin parar',
    duration: 40,
    segments: [
      { segmentDuration: 10, cadence: 70, beatsPerMinute: 120 },
      { segmentDuration: 20, cadence: 80, beatsPerMinute: 150 },
      { segmentDuration: 10, cadence: 75, beatsPerMinute: 130 },
    ],
  },
  {
    id: 12,
    exerciseType: 'Velocidad',
    name: 'Flash special',
    description: 'Ejercicio para intentar empujar la velocidad maxima del ciclista',
    duration: 90,
    segments: [
      { segmentDuration: 30, cadence: 95, beatsPerMinute: 145 },
      { segmentDuration: 30, cadence: 100, beatsPerMinute: 150 },
      { segmentDuration: 30, cadence: 105, beatsPerMinute: 155 },
    ],
  },
  {
    id: 13,
    exerciseType: 'Resistencia',
    name: 'Aguante en alta cadencia',
    description: 'Mantener una cadencia decente durante mucho tiempo en bici fija, con pausas',
    duration: 180,
    segments: [
      { segmentDuration: 60, cadence: 85, beatsPerMinute: 130 },
      { segmentDuration: 60, cadence: 90, beatsPerMinute: 135 },
      { segmentDuration: 60, cadence: 95, beatsPerMinute: 140 },
    ],
  },
  {
    id: 14,
    exerciseType: 'Fuerza',
    name: 'Resistencia',
    description: 'Resistencia mediano',
    duration: 30,
    segments: [
      { segmentDuration: 10, cadence: 70, beatsPerMinute: 120 },
      { segmentDuration: 10, cadence: 75, beatsPerMinute: 125 },
      { segmentDuration: 10, cadence: 80, beatsPerMinute: 130 },
    ],
  },
  {
    id: 15,
    exerciseType: 'Cadencia',
    name: 'Calentamiento',
    description: 'Unos minutos de cadencia media para calentar',
    duration: 20,
    segments: [
      { segmentDuration: 5, cadence: 70, beatsPerMinute: 120 },
      { segmentDuration: 5, cadence: 75, beatsPerMinute: 125 },
      { segmentDuration: 5, cadence: 80, beatsPerMinute: 130 },
    ],
  },
  {
    id: 16,
    exerciseType: 'Fuerza',
    name: 'Bici dura con pausas',
    description: 'Alternar entre cadencia baja con bici dura y cadencia alta con bici floja.',
    duration: 80,
    segments: [
      { segmentDuration: 25, cadence: 60, beatsPerMinute: 110 },
      { segmentDuration: 15, cadence: 70, beatsPerMinute: 120 },
      { segmentDuration: 25, cadence: 80, beatsPerMinute: 130 },
    ],
  },
  {
    id: 17,
    exerciseType: 'Fuerza',
    name: 'Michelin special',
    description: 'En bicicleta con rueda atada atras. ',
    duration: 60,
    segments: [
      { segmentDuration: 15, cadence: 60, beatsPerMinute: 110 },
      { segmentDuration: 15, cadence: 65, beatsPerMinute: 115 },
      { segmentDuration: 15, cadence: 70, beatsPerMinute: 120 },
    ],
  },
  {
    id: 18,
    exerciseType: 'Velocidad',
    name: 'Cardio basico',
    description: 'Ejercicio de velocidad alta para entrenar cardio',
    duration: 55,
    segments: [
      { segmentDuration: 15, cadence: 85, beatsPerMinute: 135 },
      { segmentDuration: 20, cadence: 90, beatsPerMinute: 140 },
      { segmentDuration: 20, cadence: 95, beatsPerMinute: 145 },
    ],
  },
  {
    id: 19,
    exerciseType: 'Velocidad',
    name: 'Burst',
    description: 'Ejercicio de aceleracion, estrechos cortos de alta velocidad',
    duration: 40,
    segments: [
      { segmentDuration: 10, cadence: 100, beatsPerMinute: 150 },
      { segmentDuration: 10, cadence: 110, beatsPerMinute: 160 },
      { segmentDuration: 10, cadence: 120, beatsPerMinute: 170 },
    ],
  },
  {
    id: 20,
    exerciseType: 'Velocidad',
    name: 'Burst intenso',
    description: 'Muchos estrechos cortos de alta velocidad',
    duration: 100,
    segments: [
      { segmentDuration: 25, cadence: 100, beatsPerMinute: 160 },
      { segmentDuration: 25, cadence: 105, beatsPerMinute: 165 },
      { segmentDuration: 25, cadence: 110, beatsPerMinute: 170 },
      { segmentDuration: 25, cadence: 115, beatsPerMinute: 175 },
    ],
  },
];
export default presetExercises;