const presetExercises = [
  {
    id: 1,
    exerciseType: 'Velocidad',
    name: 'Velocidad Ligero',
    description: 'Entrenamiento enfocado en velocidad para principiantes',
    duration: 60,
    segments: [
      { segmentDuration: 15, cadence: 80, beatsPerMinute: 130 },
      { segmentDuration: 15, cadence: 85, beatsPerMinute: 135 },
      { segmentDuration: 15, cadence: 90, beatsPerMinute: 140 },
      { segmentDuration: 15, cadence: 95, beatsPerMinute: 145 },
    ],
    title: '<i class="icon material-icons">directions_bike</i> Velocidad Ligero',
    class: 'speed',
  },
  {
    id: 2,
    exerciseType: 'Resistencia',
    name: 'Resistencia Ligero',
    description: 'Entrenamiento enfocado en resistencia para principiantes',
    duration: 90,
    segments: [
      { segmentDuration: 30, cadence: 70, beatsPerMinute: 120 },
      { segmentDuration: 30, cadence: 75, beatsPerMinute: 125 },
      { segmentDuration: 30, cadence: 80, beatsPerMinute: 130 },
    ],
    title: '<i class="icon material-icons">directions_run</i> Resistencia Ligero',
    class: 'resistance',
  },
  {
    id: 3,
    exerciseType: 'Cadencia',
    name: 'Cadencia Ligero',
    description: 'Entrenamiento enfocado en cadencia para principiantes',
    duration: 60,
    segments: [
      { segmentDuration: 20, cadence: 85, beatsPerMinute: 130 },
      { segmentDuration: 20, cadence: 90, beatsPerMinute: 135 },
      { segmentDuration: 20, cadence: 95, beatsPerMinute: 140 },
    ],
    title: '<i class="icon material-icons">timer</i> Cadencia Ligero',
    class: 'cadency',
  },
  {
    id: 4,
    exerciseType: 'Fuerza',
    name: 'Fuerza Ligero',
    description: 'Entrenamiento enfocado en fuerza para principiantes',
    duration: 30,
    segments: [
      { segmentDuration: 10, cadence: 60, beatsPerMinute: 110 },
      { segmentDuration: 10, cadence: 65, beatsPerMinute: 115 },
      { segmentDuration: 10, cadence: 70, beatsPerMinute: 120 },
    ],
    title: '<i class="icon material-icons">fitness_center</i> Fuerza Ligero',
    class: 'strength',
  },
  {
    id: 5,
    exerciseType: 'Fuerza',
    name: 'Fuerza Intenso',
    description: 'Entrenamiento colina arriba para practicar fuerza. No apto para principiantes',
    duration: 45,
    segments: [
      { segmentDuration: 15, cadence: 55, beatsPerMinute: 100 },
      { segmentDuration: 15, cadence: 60, beatsPerMinute: 105 },
      { segmentDuration: 15, cadence: 65, beatsPerMinute: 110 },
    ],
    title: '<i class="icon material-icons">fitness_center</i> Fuerza Intenso',
    class: 'strength',
  },
  {
    id: 6,
    exerciseType: 'Fuerza',
    name: 'Fuerza Intenso con Pausa',
    description: 'Similar a Fuerza Intenso pero con pausas mas largas entre segmentos',
    duration: 65,
    segments: [
      { segmentDuration: 20, cadence: 50, beatsPerMinute: 95 },
      { segmentDuration: 15, cadence: 55, beatsPerMinute: 100 },
      { segmentDuration: 20, cadence: 60, beatsPerMinute: 105 },
    ],
    title: '<i class="icon material-icons">fitness_center</i> Fuerza Intenso con Pausa',
    class: 'strength',
  },
  {
    id: 7,
    exerciseType: 'Resistencia',
    name: 'Tour de France',
    description: 'Entrenamiento extremo de aguante',
    duration: 430,
    segments: [
      { segmentDuration: 120, cadence: 70, beatsPerMinute: 120 },
      { segmentDuration: 120, cadence: 75, beatsPerMinute: 125 },
      { segmentDuration: 120, cadence: 80, beatsPerMinute: 130 },
    ],
    title: '<i class="icon material-icons">directions_run</i> Tour de France',
    class: 'resistance',
  },
  {
    id: 8,
    exerciseType: 'Resistencia',
    name: 'Vuelta al Mundo',
    description: 'Recorrido por todo el cuadrado de la plata',
    duration: 300,
    segments: [
      { segmentDuration: 80, cadence: 65, beatsPerMinute: 110 },
      { segmentDuration: 80, cadence: 70, beatsPerMinute: 115 },
      { segmentDuration: 80, cadence: 75, beatsPerMinute: 120 },
    ],
    title: '<i class="icon material-icons">directions_run</i> Vuelta al Mundo',
    class: 'resistance',
  },
  {
    id: 9,
    exerciseType: 'Velocidad',
    name: 'Carrera Alterna',
    description: 'Camino por el bosque a máxima velocidad',
    duration: 40,
    segments: [
      { segmentDuration: 10, cadence: 90, beatsPerMinute: 140 },
      { segmentDuration: 10, cadence: 95, beatsPerMinute: 145 },
      { segmentDuration: 10, cadence: 100, beatsPerMinute: 150 },
    ],
    title: '<i class="icon material-icons">directions_bike</i> Carrera Alterna',
    class: 'speed',
  },
  {
    id: 10,
    exerciseType: 'Cadencia',
    name: 'Bici Fija RPM',
    description: '20 minutos de calentamiento, ejercicio, 20 mins para bajar.',
    duration: 180,
    segments: [
      { segmentDuration: 20, cadence: 60, beatsPerMinute: 100 },
      { segmentDuration: 60, cadence: 85, beatsPerMinute: 135 },
      { segmentDuration: 60, cadence: 90, beatsPerMinute: 140 },
      { segmentDuration: 20, cadence: 60, beatsPerMinute: 100 },
    ],
    title: '<i class="icon material-icons">timer</i> Bici Fija RPM',
    class: 'cadency',
  },
  {
    id: 11,
    exerciseType: 'Fuerza',
    name: 'Bici en Cambio Duro',
    description: '10 minutos de calentamiento en configuración tranqui, luego cambio a duro sin parar',
    duration: 40,
    segments: [
      { segmentDuration: 10, cadence: 70, beatsPerMinute: 120 },
      { segmentDuration: 20, cadence: 80, beatsPerMinute: 150 },
      { segmentDuration: 10, cadence: 75, beatsPerMinute: 130 },
    ],
    title: '<i class="icon material-icons">fitness_center</i> Bici en Cambio Duro',
    class: 'strength',
  },
  {
    id: 12,
    exerciseType: 'Velocidad',
    name: 'Flash Special',
    description: 'Ejercicio para intentar empujar la velocidad máxima del ciclista',
    duration: 90,
    segments: [
      { segmentDuration: 30, cadence: 95, beatsPerMinute: 145 },
      { segmentDuration: 30, cadence: 100, beatsPerMinute: 150 },
      { segmentDuration: 30, cadence: 105, beatsPerMinute: 155 },
    ],
    title: '<i class="icon material-icons">directions_bike</i> Flash Special',
    class: 'speed',
  },
  {
    id: 13,
    exerciseType: 'Resistencia',
    name: 'Aguante en Alta Cadencia',
    description: 'Mantener una cadencia decente durante mucho tiempo en bici fija, con pausas',
    duration: 180,
    segments: [
      { segmentDuration: 60, cadence: 85, beatsPerMinute: 130 },
      { segmentDuration: 60, cadence: 90, beatsPerMinute: 135 },
      { segmentDuration: 60, cadence: 95, beatsPerMinute: 140 },
    ],
    title: '<i class="icon material-icons">directions_run</i> Aguante en Alta Cadencia',
    class: 'resistance',
  },
  {
    id: 14,
    exerciseType: 'Fuerza',
    name: 'Resistencia Mediano',
    description: 'Resistencia mediano',
    duration: 30,
    segments: [
      { segmentDuration: 10, cadence: 70, beatsPerMinute: 120 },
      { segmentDuration: 10, cadence: 75, beatsPerMinute: 125 },
      { segmentDuration: 10, cadence: 80, beatsPerMinute: 130 },
    ],
    title: '<i class="icon material-icons">fitness_center</i> Resistencia Mediano',
    class: 'strength',
  },
  {
    id: 15,
    exerciseType: 'Cadencia',
    name: 'Calentamiento',
    description: 'Unos minutos de cadencia media para calentar',
    duration: 20,
    segments: [
      { segmentDuration: 5, cadence: 70, beatsPerMinute: 120 },
      { segmentDuration: 5, cadence: 75, beatsPerMinute: 125 },
      { segmentDuration: 5, cadence: 80, beatsPerMinute: 130 },
    ],
    title: '<i class="icon material-icons">timer</i> Calentamiento',
    class: 'cadency',
  },
  {
    id: 16,
    exerciseType: 'Fuerza',
    name: 'Bici Dura con Pausas',
    description: 'Alternar entre cadencia baja con bici dura y cadencia alta con bici floja.',
    duration: 80,
    segments: [
      { segmentDuration: 25, cadence: 60, beatsPerMinute: 110 },
      { segmentDuration: 15, cadence: 70, beatsPerMinute: 120 },
      { segmentDuration: 25, cadence: 80, beatsPerMinute: 130 },
    ],
    title: '<i class="icon material-icons">fitness_center</i> Bici Dura con Pausas',
    class: 'strength',
  },
  {
    id: 17,
    exerciseType: 'Fuerza',
    name: 'Michelin Special',
    description: 'En bicicleta con rueda atada atrás.',
    duration: 60,
    segments: [
      { segmentDuration: 15, cadence: 60, beatsPerMinute: 110 },
      { segmentDuration: 15, cadence: 65, beatsPerMinute: 115 },
      { segmentDuration: 15, cadence: 70, beatsPerMinute: 120 },
    ],
    title: '<i class="icon material-icons">fitness_center</i> Michelin Special',
    class: 'strength',
  },
  {
    id: 18,
    exerciseType: 'Velocidad',
    name: 'Cardio Básico',
    description: 'Ejercicio de velocidad alta para entrenar cardio',
    duration: 55,
    segments: [
      { segmentDuration: 15, cadence: 85, beatsPerMinute: 135 },
      { segmentDuration: 20, cadence: 90, beatsPerMinute: 140 },
      { segmentDuration: 20, cadence: 95, beatsPerMinute: 145 },
    ],
    title: '<i class="icon material-icons">directions_bike</i> Cardio Básico',
    class: 'speed',
  },
  {
    id: 19,
    exerciseType: 'Velocidad',
    name: 'Burst',
    description: 'Ejercicio de aceleración, estrechos cortos de alta velocidad',
    duration: 40,
    segments: [
      { segmentDuration: 10, cadence: 100, beatsPerMinute: 150 },
      { segmentDuration: 10, cadence: 110, beatsPerMinute: 160 },
      { segmentDuration: 10, cadence: 120, beatsPerMinute: 170 },
    ],
    title: '<i class="icon material-icons">directions_bike</i> Burst',
    class: 'speed',
  },
  {
    id: 20,
    exerciseType: 'Velocidad',
    name: 'Burst Intenso',
    description: 'Muchos estrechos cortos de alta velocidad',
    duration: 100,
    segments: [
      { segmentDuration: 25, cadence: 100, beatsPerMinute: 160 },
      { segmentDuration: 25, cadence: 105, beatsPerMinute: 165 },
      { segmentDuration: 25, cadence: 110, beatsPerMinute: 170 },
      { segmentDuration: 25, cadence: 115, beatsPerMinute: 175 },
    ],
    title: '<i class="icon material-icons">directions_bike</i> Burst Intenso',
    class: 'speed',
  },
];

export default presetExercises;
